switched back to MD5 instead of diff for tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -166,6 +166,7 @@ jobs:
             echo "  OUTPUT_MD5:   $OUTPUT_MD5"
             exit 1
           fi
+          
       - name: Run polyphonia (cross_contamination test with aligned consensus sequences)
         run: |
           set -e -x
@@ -178,17 +179,17 @@ jobs:
             --output /tmp/output/potential_cross-contamination.txt \
             --overwrite TRUE
             
-          DIFF=$(diff $(pwd)/output/potential_cross-contamination.txt ${{ env.DOCKER_POLYPHONIA_PATH }}/test/output/potential_cross-contamination.txt) 
-          if [ "$DIFF" != "" ]; then
-            echo "Failure: cross_contamination test output does not match expected output"
-            echo "  expected output:"
-            cat $(pwd)/output/potential_cross-contamination.txt
-            echo "  test output:"
-            cat ${{ env.DOCKER_POLYPHONIA_PATH }}/test/output/potential_cross-contamination.txt
-            exit 1
-          else
+          EXPECTED_MD5="358d736c9bd513731c020f84b7b06376"
+          OUTPUT_MD5="$(md5sum $(pwd)/output/potential_cross-contamination.txt | awk '{ print $1 }')"
+          if [[ "$OUTPUT_MD5" == "$EXPECTED_MD5" ]]; then
             echo "Success: cross_contamination test"
+          else
+            echo "Failure: cross_contamination test output does not match expected file hash"
+            echo "  EXPECTED_MD5: $EXPECTED_MD5"
+            echo "  OUTPUT_MD5:   $OUTPUT_MD5"
+            exit 1
           fi
+          
       - name: Run polyphonia (cross_contamination test with aligned consensus sequences with gap in reference)
         run: |
           set -e -x
