tried adding diff test of output file again?

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -167,6 +167,18 @@ jobs:
             exit 1
           fi
           
+          DIFF=$(diff $(pwd)/output/potential_cross-contamination.txt ${{ env.DOCKER_POLYPHONIA_PATH }}/test/output/potential_cross-contamination.txt) 
+          if [ "$DIFF" != "" ]; then
+            echo "Failure: cross_contamination test output does not match expected output"
+            echo "  expected output:"
+            cat $(pwd)/output/potential_cross-contamination.txt
+            echo "  test output:"
+            cat ${{ env.DOCKER_POLYPHONIA_PATH }}/test/output/potential_cross-contamination.txt
+            exit 1
+          else
+            echo "Success: cross_contamination test"
+          fi
+          
       - name: Run polyphonia (cross_contamination test with aligned consensus sequences)
         run: |
           set -e -x
